server:
  port: 8160

spring:
  application:
    name: gateway

  #启用DiscoveryClient网关集成，可以实现服务的发现
  cloud:
    gateway:
      enabled: true
      #配置网关路由转发规则
      routes:
        - id: service-bbs
          #负载均衡调用service-bbs服务
          uri: lb://service-bbs
          predicates:
            - Path=/bbs/**

        - id: service-course
          #负载均衡调用service-course服务
          uri: lb://service-course
          predicates:
            - Path=/cms/**

        - id: service-download
          #负载均衡调用service-download服务
          uri: lb://service-download
          predicates:
            - Path=/dtm/**

        - id: service-message
          #负载均衡调用service-message服务
          uri: lb://service-message
          predicates:
            - Path=/message/**

        - id: service-oss
          #负载均衡调用service-oss服务
          uri: lb://service-oss
          predicates:
            - Path=/oss/**

        - id: service-ucenter
          #负载均衡调用service-ucenter服务
          uri: lb://service-ucenter
          predicates:
            - Path=/user/**

        - id: service-vip
          #负载均衡调用service-vip服务
          uri: lb://service-vip
          predicates:
            - Path=/vm/**

        - id: service-vod
          #负载均衡调用service-vod服务
          uri: lb://service-vod
          predicates:
            - Path=/vod/**


    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 430293a0-4969-4c8f-8732-e12ba198d06a
        group: kuangstudy
      username: nacos
      password: nacos


